#!/usr/bin/env python3
"""
Verification script to confirm JWT configuration is working correctly.
This demonstrates that Flask-JWT-Extended reads JWT_SECRET_KEY from app.config.
"""

import os
import sys

# Add src to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from app import create_app

def verify_jwt_config():
    """Verify JWT configuration is properly set up"""
    print("=" * 70)
    print("JWT Configuration Verification")
    print("=" * 70)

    # Create app
    app = create_app('development')

    with app.app_context():
        print("\n1. Environment Variables (.env file):")
        print(f"   JWT_ACCESS_SECRET: {os.getenv('JWT_ACCESS_SECRET', 'NOT SET (using default)')}")
        print(f"   JWT_REFRESH_SECRET: {os.getenv('JWT_REFRESH_SECRET', 'NOT SET (using default)')}")

        print("\n2. Config Class (src/config.py):")
        print(f"   JWT_ACCESS_SECRET_KEY: {app.config.get('JWT_ACCESS_SECRET_KEY', 'NOT SET')[:20]}...")
        print(f"   JWT_REFRESH_SECRET_KEY: {app.config.get('JWT_REFRESH_SECRET_KEY', 'NOT SET')[:20]}...")

        print("\n3. Flask-JWT-Extended Config (what it reads):")
        print(f"   JWT_SECRET_KEY: {app.config.get('JWT_SECRET_KEY', 'NOT SET')[:20]}...")
        print(f"   JWT_ACCESS_TOKEN_EXPIRES: {app.config.get('JWT_ACCESS_TOKEN_EXPIRES')}")
        print(f"   JWT_REFRESH_TOKEN_EXPIRES: {app.config.get('JWT_REFRESH_TOKEN_EXPIRES')}")
        print(f"   JWT_TOKEN_LOCATION: {app.config.get('JWT_TOKEN_LOCATION')}")
        print(f"   JWT_HEADER_TYPE: {app.config.get('JWT_HEADER_TYPE')}")

        print("\n4. Verification:")
        access_key = app.config.get('JWT_ACCESS_SECRET_KEY')
        jwt_key = app.config.get('JWT_SECRET_KEY')

        if access_key == jwt_key:
            print("   ✅ JWT_SECRET_KEY correctly set to JWT_ACCESS_SECRET_KEY")
        else:
            print("   ❌ JWT_SECRET_KEY does NOT match JWT_ACCESS_SECRET_KEY")
            print(f"      JWT_ACCESS_SECRET_KEY: {access_key[:20]}...")
            print(f"      JWT_SECRET_KEY: {jwt_key[:20]}...")

        print("\n5. Token Generation Test:")
        from services.token_service import TokenService

        try:
            # Test access token (uses Flask-JWT-Extended)
            access_token = TokenService.generate_access_token('test-user-id', {'role': 'guest'})
            print(f"   ✅ Access token generated: {access_token[:50]}...")

            # Test refresh token (uses PyJWT directly)
            refresh_token = TokenService.generate_refresh_token('test-user-id', {'sessionId': '123'})
            print(f"   ✅ Refresh token generated: {refresh_token[:50]}...")

            # Verify refresh token
            payload = TokenService.verify_refresh_token(refresh_token)
            print(f"   ✅ Refresh token verified: user_id={payload.get('sub')}")

        except Exception as e:
            print(f"   ❌ Token generation/verification failed: {e}")

        print("\n" + "=" * 70)
        print("Configuration Summary:")
        print("=" * 70)
        print("""
Access Tokens:
  - Signed with: JWT_SECRET_KEY (from app.config)
  - Which equals: JWT_ACCESS_SECRET_KEY
  - From env var: JWT_ACCESS_SECRET
  - Generated by: Flask-JWT-Extended's create_access_token()
  - Verified by: Flask-JWT-Extended's verify_jwt_in_request()

Refresh Tokens:
  - Signed with: JWT_REFRESH_SECRET_KEY (from app.config)
  - From env var: JWT_REFRESH_SECRET
  - Generated by: TokenService.generate_refresh_token() using PyJWT
  - Verified by: TokenService.verify_refresh_token() using PyJWT

This matches the NestJS configuration:
  - NestJS JWT_ACCESS_SECRET  → Flask JWT_ACCESS_SECRET
  - NestJS JWT_REFRESH_SECRET → Flask JWT_REFRESH_SECRET
        """)
        print("=" * 70)

if __name__ == '__main__':
    verify_jwt_config()
